Repository Skyrat-SS13/Vesta.Bay, pull requests merged in 2021-08, with the labels that each got.

#3 Moves Configs outside of Examples
  config/admin_ranks.txt
  config/admins.txt
  config/alienwhitelist.txt
  config/away_site_blacklist.txt
  config/config.txt
  config/custom_sprites.txt
  config/dbconfig.txt
  config/dbconfig_docker.txt
  config/exoplanet_ruin_blacklist.txt
  config/game_options.txt
  config/jobs.txt
  config/jobwhitelist.txt
  config/lore.html
  config/moderators.txt
  config/motd.txt
  config/rules.html
  config/space_ruin_blacklist.txt
  config/torch_config.txt
  config/webhooks.json
Labels: Initial Configurations

#2 [DNM] CONFIG UPDATES TO THE TGS
  config/example/config.txt
Labels: Config

#1 [DNM] CONFIG updates! FOR THE TGS!
  config/example/torch_config.txt
Labels: Config

#18 Cookies now can be spammed from pray
  code/modules/admin/topic.dm
Labels: bug fix

#19 Fixing the sign in bug, attempt one.
  code/modules/client/preferences.dm
  code/modules/mob/new_player/new_player.dm
Labels: bug fix
