Repository Skyrat-SS13/Vesta.Bay, pull requests merged in 2021-09, with the labels that each got.

#23 log fixes
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/getlogs.dm
Labels: bug fix

#29 Phoron Restructurant Human bugfixes
  code/modules/client/preference_setup/loadout/loadout.dm
  icons/obj/storage.dmi
  modular_boh/code/modules/species/plasmasans_mob/plasmasans.dm
Labels: Fix

#30 Change the forum hub link to our Discord.
  code/game/world.dm
Labels: Internal Change, Speed Merge

#32 Update whitelist!
  config/alienwhitelist.txt
  config/config.txt
Labels: Config Update

#31 SM alerts to general for low pop
  code/modules/supermatter/supermatter.dm
Labels: Tweak

#36 Farson map fixes
  baystation12.dme
  code/_helpers/matrices.dm
  code/datums/observation/supermatter_status.dm
  code/game/machinery/wall_frames.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/recipes_items.dm
  code/modules/supermatter/supermatter.dm
  icons/obj/supermatter.dmi
  maps/torch/torch1_deck5.dmm
  maps/torch/torch2_deck4.dmm
  maps/torch/torch3_deck3.dmm
  maps/torch/torch4_deck2.dmm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch6_bridge.dmm
  modular_boh/code/modules/power/lighting.dm
  modular_boh/code/modules/torch_security_state.dm
  sound/misc/alert09.ogg
Labels: Enhancement

#42 QOL Changes 2: Electric Boogaloo 2 (Electric Boogaloo)
  baystation12.dme
  code/game/machinery/doors/airlock.dm
  code/game/machinery/wall_frames.dm
  code/modules/supermatter/supermatter.dm
  icons/obj/supermatter.dmi
  maps/torch/torch1_deck5.dmm
  maps/torch/torch2_deck4.dmm
  maps/torch/torch3_deck3.dmm
  maps/torch/torch4_deck2.dmm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch6_bridge.dmm
Labels: Fix

#16 Defibrillation now works on deceased.
  code/game/objects/items/weapons/defib.dm
  code/modules/surgery/organs_internal.dm
Labels: Enhancement, Balance/Rebalance

#48 Map fixes 2
  baystation12.dme
  code/modules/admin/admin_verbs.dm
  code/modules/supermatter/supermatter.dm
  maps/torch/torch4_deck2.dmm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch6_bridge.dmm
Labels: Needs Squashed

#59 Adds DMAPI v4.14.3
  baystation12.dme
  code/__defines/tgs.config.dm
  code/__defines/tgs.dm
  code/controllers/master.dm
  code/game/world.dm
  code/modules/tgs/LICENSE
  code/modules/tgs/README.md
  code/modules/tgs/core/README.md
  code/modules/tgs/core/_definitions.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/core/tgs_version.dm
  code/modules/tgs/includes.dm
  code/modules/tgs/v3210/README.md
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v3210/commands.dm
  code/modules/tgs/v4/README.md
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v4/commands.dm
  code/modules/tgs/v5/README.md
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/commands.dm
  code/modules/tgs/v5/interop_version.dm
  code/modules/tgs/v5/undefs.dm
Labels: Enhancement, Internal Change
